/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        TestCases tests = new TestCases(); // Initialize your test class

        // INTV-1/Session-7/2/Activity 7: Automate_nested_frames_text
        tests.TC_AutomateNestedFramesText();

        // // INTV-1/Session-7/3/Automate_Alert_Prompt
        // tests.TC_AutomateAlertPrompt();

        //END Tests


        tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
